world:
  name: Sandstone
  description: 'A sample map used to test new BlueDragon minigames.'
  author: 'BlueDragon Build Team'
  spawnpoints:
    - 7.5, 59.5, -34.5, 0, 0
    - -2.5, 64, -11.5, 0, 0
    - -11.5, 64, 2.5, -90, 0
    - 2.5, 64, 11.5, 180, 0
    - 13.5, 64, -3.5, 90, 0
    - -1.5, 77, 5.5, -90, 0
burnableRegionsStage1:
  - name: <yellow><lang:firefighters.factory_1>
    start: -7, 64, 0
    end: -7, 66, 0
burnableRegionsStage2:
  - name: <#acfc8d><lang:firefighters.reactor_core>
    start: -9, 64, 0
    end: -9, 66, 0