world:
  name: Reactor
  description: 'An industrial complex with a suspicious lack of security.'
  author: 'BlueDragon Build Team'
  spawnpoints:
    - 11, -52, 27, 90, 0
burnableRegionsStage1:
  - name: <yellow><lang:firefighters.factory_1>
    start: 34, -35, 36
    end: 12, -53, 16
  - name: <yellow><lang:firefighters.factory_2>
    start: -90, -52, 36
    end: -66, -46, 14
  - name: <yellow><lang:firefighters.factory_3>
    start: -56, -52, -80
    end: -34, -41, -58
  - name: <yellow><lang:firefighters.factory_4>
    start: 11, -52, -79
    end: 33, -41, -57
burnableRegionsStage2:
  - name: <#acfc8d><lang:firefighters.reactor_core>
    start: -7, -32, -33
    end: 4, -20, -45