world:
  name: Reactor
  description: 'An industrial complex with a suspicious lack of security.'
  author: 'BlueDragon Build Team'
  spawnpoints:
    - 11, -52, 27, 90, 0
burnableRegionsStage1:
  - name: <yellow><lang:firefighters.factory_1> # Weapon Storage
    start: 23, -53, 55
    end: 51, -31, 30
    cutscene:
      - 33.5, -50, 43, -90, 0
      - 21, -48, 43, -90, 0
      - 8.5, -34, 43, -90, 30
      - 8.5, -34, 43, -90, 30
      - 8.5, -34, 43, -90, 30
  - name: <yellow><lang:firefighters.factory_2> # Fuel Storage
    start: -90, -52, 40
    end: -66, -37, 14
    cutscene:
      - -83, -48, 33, -170, 30
      - -84, -45, 51, -180, 20
      - -95, -38, 51, -150, 30
      - -95, -38, 51, -150, 30
      - -95, -38, 51, -150, 30
  - name: <yellow><lang:firefighters.factory_3> # Food Storage
    start: -69, -53, -59
    end: -103, -33, -73
    cutscene:
      - -66, -50, -65.5, 90, 0
      - -54, -38, -65.5, 90, 30
      - -60, -33, -84, 45, 30
      - -60, -33, -84, 45, 30
      - -60, -33, -84, 45, 30
burnableRegionsStage2:
  - name: <#acfc8d><lang:firefighters.reactor_core>
    start: -7, -32, -33
    end: 4, -20, -45
    cutscene:
      - -98, -41, -65.5, -90, 20
      - -114, -38 -65.5, -90, 15
      - -120, -30, -44, -130, 20
      - -120, -30, -44, -130, 20
      - -120, -30, -44, -130, 20
powerup:
  locations:
    - 37.5, -43, 43 # in weapon storage
    - -33.5, -52, 90 # in south fire station
    - -96, -52, -15 # outside, west
    - -80, -52, -43 # outside, northwest
    - -23, -52, -62 # outside, north
    - -3, -52, -111 # in north fire station
    - 85, -52, -10 # in east fire station
    - 31, -52, -6 # outside, east
    - -10, -50, 29 # outside, south
    - -45, -52, -34 # admin building, bottom
    - -36, -47, -32 # admin building, top
    - -48.5, -52, -3.5 # turbine building
