world:
  name: Reactor
  description: 'An industrial complex with a suspicious lack of security.'
  author: 'BlueDragon Build Team'
  spawnpoints:
    - 11, -52, 27, 90, 0
burnableRegions:
  - name: <lang:firefighters.factory_1>
    start: -7, 64, 0
    end: -7, 66, 0